### ISSUE TITLE
ERR_CONNECTION_REFUSED Cloudflare

### ISSUE THREAD

**Issue by rtritto** [zfcsoftware/puppeteer-real-browser#146]
Using an URL site with _Cloudflare_.

### Code
```ts
import { connect } from 'puppeteer-real-browser'

const { page } = await connect({})

await page.goto('<URL>')
```

### Output
```console

C:\Users\<USER>\AppData\Local\Yarn\Berry\cache\puppeteer-core-patch-npm-1.0.1-95fd1d1f38-10c0.zip\node_modules\puppeteer-core-patch\src\cdp\Frame.ts:216
          ? new Error(`${response.errorText} at ${url}`)
            ^


Error: net::ERR_CONNECTION_REFUSED at <URL>
    at navigate (C:\Users\<USER>\AppData\Local\Yarn\Berry\cache\puppeteer-core-patch-npm-1.0.1-95fd1d1f38-10c0.zip\node_modules\puppeteer-core-patch\src\cdp\Frame.ts:216:13)       
    at Function.race (C:\Users\<USER>\AppData\Local\Yarn\Berry\cache\puppeteer-core-patch-npm-1.0.1-95fd1d1f38-10c0.zip\node_modules\puppeteer-core-patch\src\util\Deferred.ts:49:14)
    at CdpFrame.goto (C:\Users\<USER>\AppData\Local\Yarn\Berry\cache\puppeteer-core-patch-npm-1.0.1-95fd1d1f38-10c0.zip\node_modules\puppeteer-core-patch\src\cdp\Frame.ts:169:17)  
    at CdpPage.goto (C:\Users\<USER>\AppData\Local\Yarn\Berry\cache\puppeteer-core-patch-npm-1.0.1-95fd1d1f38-10c0.zip\node_modules\puppeteer-core-patch\lib\esm\puppeteer\api\Page.js:561:20)
    at <anonymous> (C:\<PROJECT>\start.ts:15:1)
```

### Info
puppeteer-real-browser: 1.3.3
OS: Windows

### Workaround
Add a delay of 5 seconds before _goto_ (the error appear with lower seconds)
```ts
import { setTimeout } from 'timers/promises'
...
// Add delay of 5 seconds
await setTimeout(5000)
await page.goto('<URL>')
```

**Comment by zfcsoftware** [comment]
It has been tested many times with the test file and there are no issues with Cloudflare WAF and Turnstile. There may be a momentary problem with the proxy you are using or your network. If the issue can be reproduced, please report it via this thread. Thank you.


https://github.com/user-attachments/assets/8b604a5b-d5cd-40aa-a42a-930983a14d62
