### ISSUE TITLE
"Error: target should exist before targetInfoChanged" on MacOS

### ISSUE THREAD

**Issue by joyqi** [zfcsoftware/puppeteer-real-browser#68]
Run example codes on my Macbook mini M1:

```js
import { connect } from 'puppeteer-real-browser'

connect({
    turnstile: true
})
.then(async response => {
        const { page, browser, setTarget } = response

        page.goto('https://nopecha.com/demo/cloudflare', {
            waitUntil: 'domcontentloaded'
        })

        setTarget({ status: false })

        let page2 = await browser.newPage();

        setTarget({ status: true })

        await page2.goto('https://nopecha.com/demo/cloudflare');
})
```

Got a strange error:

```
/Users/joyqi/Work/domain-price-crawler/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26
        throw new Error(message);
              ^

Error: target should exist before targetInfoChanged
    at Object.assert (/Users/joyqi/Work/domain-price-crawler/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
    at Browser._targetInfoChanged (/Users/joyqi/Work/domain-price-crawler/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:210:21)
    at /Users/joyqi/Work/domain-price-crawler/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (/Users/joyqi/Work/domain-price-crawler/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
    at Connection.emit (/Users/joyqi/Work/domain-price-crawler/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at Connection._onMessage (/Users/joyqi/Work/domain-price-crawler/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:125:18)
    at WebSocket.<anonymous> (/Users/joyqi/Work/domain-price-crawler/node_modules/puppeteer/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:13:32)
    at WebSocket.onMessage (/Users/joyqi/Work/domain-price-crawler/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (node:events:517:28)

Node.js v18.19.1
```

**Comment by zfcsoftware** [comment]
This problem should be solved. Can you check again with the latest version?
